colors:
  # Default colors
  primary:
    background: '0xf5e7de'
    foreground: '0x34302d'

  # Normal colors
  normal:
    black:   '0x666661'
    red:     '0x992e2e'
    green:   '0x4c3226'
    yellow:  '0xa67c53'
    blue:    '0x4c7399'
    magenta: '0xbf9986'
    cyan:    '0xd97742'
    white:   '0x34302d'

  # Bright colors
  bright:
    black:   '0x7f7f7a'
    red:     '0xb23636'
    green:   '0x664233'
    yellow:  '0xbf8f60'
    blue:    '0x5986b2'
    magenta: '0xd9ae98'
    cyan:    '0xf2854a'
    white:   '0x4c4742'
