colors:
  # Default colors
  primary:
    background: '0x272822'
    foreground: '0xf1ebeb'

  # Normal colors
  normal:
    black:   '0x48483e'
    red:     '0xdc2566'
    green:   '0x8fc029'
    yellow:  '0xd4c96e'
    blue:    '0x55bcce'
    magenta: '0x9358fe'
    cyan:    '0x56b7a5'
    white:   '0xacada1'

  # Bright colors
  bright:
    black:   '0x76715e'
    red:     '0xfa2772'
    green:   '0xa7e22e'
    yellow:  '0xe7db75'
    blue:    '0x66d9ee'
    magenta: '0xae82ff'
    cyan:    '0x66efd5'
    white:   '0xcfd0c2'
