colors:
  # Default colors
  primary:
    background: '0x181512'
    foreground: '0xbea492'

  # Normal colors
  normal:
    black:   '0x332d29'
    red:     '0x8c644c'
    green:   '0x746c48'
    yellow:  '0x908a66'
    blue:    '0x646a6d'
    magenta: '0x605655'
    cyan:    '0x4b5c5e'
    white:   '0x504339'

  # Bright colors
  bright:
    black:   '0x817267'
    red:     '0x9f7155'
    green:   '0x857b52'
    yellow:  '0x9c956e'
    blue:    '0x71777a'
    magenta: '0x656565'
    cyan:    '0x556d70'
    white:   '0x9a875f'
